const initialUsers = [
  {
    userId: 'USR001',
    username: 'superadmin',
    password: 'SuperAdmin@123',
    name: 'Super Administrator',
    email: 'superadmin@zenithschools.edu.in',
    phone: '+91 98401 11223',
    role: 'superadmin',
    schoolId: 'ALL',
    schoolName: 'Zenith Central Trust',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
  },
  {
    userId: 'USR002',
    username: 'admin_ssv',
    password: 'admin123',
    name: 'R. K. Meenakshi Sundaram',
    email: 'admin.ssv@zenithschools.edu.in',
    phone: '+91 98402 33445',
    role: 'schooladmin',
    schoolId: 'SCH001',
    schoolName: 'Zenith International Girls Higher Secondary School',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
  },
  {
    userId: 'USR003',
    username: 'principal_ssv',
    password: 'principal123',
    name: 'Dr. Sunita Sharma, M.Sc., Ph.D.',
    email: 'principal@zenithschools.edu.in',
    phone: '+91 98403 44556',
    role: 'principal',
    schoolId: 'SCH001',
    schoolName: 'Zenith International Girls Higher Secondary School',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
  },
  {
    userId: 'USR004',
    username: 'teacher_priya',
    password: 'teacher123',
    name: 'Mrs. Priya Ramanathan',
    email: 'priya.r@zenithschools.edu.in',
    phone: '+91 98404 55667',
    role: 'teacher',
    schoolId: 'SCH001',
    schoolName: 'Zenith International Girls Higher Secondary School',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
  },
  {
    userId: 'USR005',
    username: 'teacher_anand',
    password: 'teacher123',
    name: 'Mr. Anand Narayanan',
    email: 'anand.n@zenithschools.edu.in',
    phone: '+91 98405 66778',
    role: 'teacher',
    schoolId: 'SCH001',
    schoolName: 'Zenith International Girls Higher Secondary School',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
  },
  {
    userId: 'USR006',
    username: 'student_ananya',
    password: 'student123',
    name: 'Ananya S. Krishnan',
    email: 'ananya.k@student.zenithschools.edu.in',
    phone: '+91 98406 77889',
    role: 'student',
    schoolId: 'SCH001',
    schoolName: 'Zenith International Girls Higher Secondary School',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
  },
  {
    userId: 'USR007',
    username: 'student_divya',
    password: 'student123',
    name: 'Divya M. Venkatesh',
    email: 'divya.v@student.zenithschools.edu.in',
    phone: '+91 98407 88990',
    role: 'student',
    schoolId: 'SCH001',
    schoolName: 'Zenith International Girls Higher Secondary School',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80',
  },
  {
    userId: 'USR008',
    username: 'parent_krishnan',
    password: 'parent123',
    name: 'S. Krishnan (Parent of Ananya)',
    email: 'krishnan.s@gmail.com',
    phone: '+91 98408 99001',
    role: 'parent',
    schoolId: 'SCH001',
    schoolName: 'Zenith International Girls Higher Secondary School',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
  },
  {
    userId: 'USR009',
    username: 'admin_gvn',
    password: 'admin123',
    name: 'S. Vijayalakshmi',
    email: 'admin.gvn@zenithschools.edu.in',
    phone: '+91 98409 11224',
    role: 'schooladmin',
    schoolId: 'SCH002',
    schoolName: 'Zenith Vidyalaya Matriculation Higher Secondary School',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
  },
];

const initialSchools = [
  {
    schoolId: 'SCH001',
    name: 'Zenith International Girls Higher Secondary School',
    code: 'SSV-01',
    board: 'CBSE',
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: '42, Dr. Radhakrishnan Salai, Mylapore, Chennai',
    principalName: 'Dr. Sunita Sharma',
    email: 'admin@zenithgirls.edu.in',
    phone: '+91 44 2844 1122',
    studentCount: 1250,
    teacherCount: 68,
    plan: 'Enterprise',
    status: 'Active',
    joinedDate: '2023-01-15',
  },
  {
    schoolId: 'SCH002',
    name: 'Zenith Vidyalaya Matriculation School',
    code: 'ZVM-02',
    board: 'State Board',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    address: '15, Avinashi Road, Peelamedu, Coimbatore',
    principalName: 'S. Vijayalakshmi',
    email: 'admin.gvn@zenithschools.edu.in',
    phone: '+91 422 257 8899',
    studentCount: 820,
    teacherCount: 42,
    plan: 'Professional',
    status: 'Active',
    joinedDate: '2023-06-20',
  },
  {
    schoolId: 'SCH003',
    name: 'Zenith Model Higher Secondary School',
    code: 'ZMH-03',
    board: 'ICSE',
    city: 'Madurai',
    state: 'Tamil Nadu',
    address: '88, Alagar Kovil Road, Madurai',
    principalName: 'K. Rajasekaran',
    email: 'info@zenithmadurai.edu.in',
    phone: '+91 452 253 4400',
    studentCount: 640,
    teacherCount: 35,
    plan: 'Standard',
    status: 'Active',
    joinedDate: '2024-02-10',
  },
];

const initialStudents = [
  {
    studentId: 'STD001',
    name: 'Ananya S. Krishnan',
    rollNo: 'XII-A-01',
    grade: 'Class 12',
    section: 'A',
    gender: 'Female',
    dob: '2008-05-14',
    parentName: 'S. Krishnan',
    parentPhone: '+91 98408 99001',
    parentEmail: 'krishnan.s@gmail.com',
    address: '12 Temple Street, Mylapore, Chennai',
    attendancePercentage: 97.4,
    feeStatus: 'Paid',
    schoolId: 'SCH001',
  },
  {
    studentId: 'STD002',
    name: 'Divya M. Venkatesh',
    rollNo: 'XII-A-02',
    grade: 'Class 12',
    section: 'A',
    gender: 'Female',
    dob: '2008-08-22',
    parentName: 'M. Venkatesh',
    parentPhone: '+91 98407 88990',
    parentEmail: 'venkatesh.m@yahoo.com',
    address: '45 Lake View Road, Chennai',
    attendancePercentage: 94.2,
    feeStatus: 'Paid',
    schoolId: 'SCH001',
  },
  {
    studentId: 'STD003',
    name: 'Kavitha R. Sundar',
    rollNo: 'XI-B-07',
    grade: 'Class 11',
    section: 'B',
    gender: 'Female',
    dob: '2009-02-18',
    parentName: 'R. Sundar',
    parentPhone: '+91 98400 33441',
    parentEmail: 'sundar.r@gmail.com',
    address: '89 North Mada Street, Mylapore',
    attendancePercentage: 92.0,
    feeStatus: 'Pending',
    schoolId: 'SCH001',
  },
];

const initialTeachers = [
  {
    teacherId: 'TCH001',
    name: 'Mrs. Priya Ramanathan',
    empId: 'EMP-014',
    subject: 'Mathematics',
    qualification: 'M.Sc., B.Ed.',
    phone: '+91 98404 55667',
    email: 'priya.r@zenithschools.edu.in',
    classesAssigned: ['Class 12-A', 'Class 11-A', 'Class 10-B'],
    status: 'Active',
    schoolId: 'SCH001',
  },
  {
    teacherId: 'TCH002',
    name: 'Mr. Anand Narayanan',
    empId: 'EMP-022',
    subject: 'Physics',
    qualification: 'M.Sc., M.Phil.',
    phone: '+91 98405 66778',
    email: 'anand.n@zenithschools.edu.in',
    classesAssigned: ['Class 12-A', 'Class 12-B'],
    status: 'Active',
    schoolId: 'SCH001',
  },
  {
    teacherId: 'TCH003',
    name: 'Dr. Sunita Sharma',
    empId: 'EMP-001',
    subject: 'Chemistry / Administration',
    qualification: 'Ph.D., M.Ed.',
    phone: '+91 98403 44556',
    email: 'principal@zenithschools.edu.in',
    classesAssigned: ['Class 12-A'],
    status: 'Active',
    schoolId: 'SCH001',
  },
];

const initialPlans = [
  {
    planId: 'PLAN001',
    name: 'Standard Foundation',
    code: 'STD-FND',
    price: 24000,
    billingCycle: 'Annual',
    maxStudents: 500,
    maxTeachers: 40,
    features: ['Student & Staff Registry', 'Attendance Tracking', 'Exam Marks & Report Cards', 'Email Notifications'],
    status: 'Active',
  },
  {
    planId: 'PLAN002',
    name: 'Professional Campus',
    code: 'PRO-CMP',
    price: 48000,
    billingCycle: 'Annual',
    maxStudents: 1500,
    maxTeachers: 100,
    features: ['All Standard Features', 'Parent Portal & Mobile App', 'Fee Management & Online Gateway', 'Live Timetable Generator', 'SMS Gateways'],
    status: 'Active',
  },
  {
    planId: 'PLAN003',
    name: 'Enterprise Multi-Campus',
    code: 'ENT-MLT',
    price: 96000,
    billingCycle: 'Annual',
    maxStudents: 5000,
    maxTeachers: 350,
    features: ['All Pro Features', 'Multi-Campus Centralised Hub', 'Custom ERP Branding & Domain', 'Dedicated Account Manager', 'Automated Daily Backups'],
    status: 'Active',
  },
];

const initialSubscriptions = [
  {
    subscriptionId: 'SUB001',
    schoolId: 'SCH001',
    schoolName: 'Zenith International Girls Higher Secondary School',
    planName: 'Enterprise Multi-Campus',
    status: 'Active',
    startDate: '2026-01-01',
    expiryDate: '2026-12-31',
    amount: 96000,
    billingCycle: 'Annual',
    autoRenew: true,
  },
  {
    subscriptionId: 'SUB002',
    schoolId: 'SCH002',
    schoolName: 'Zenith Vidyalaya Matriculation School',
    planName: 'Professional Campus',
    status: 'Active',
    startDate: '2025-06-01',
    expiryDate: '2026-05-31',
    amount: 48000,
    billingCycle: 'Annual',
    autoRenew: true,
  },
  {
    subscriptionId: 'SUB003',
    schoolId: 'SCH003',
    schoolName: 'Zenith Model Higher Secondary School',
    planName: 'Standard Foundation',
    status: 'Expiring Soon',
    startDate: '2025-04-15',
    expiryDate: '2026-04-14',
    amount: 24000,
    billingCycle: 'Annual',
    autoRenew: false,
  },
];

const initialBills = [
  {
    invoiceNo: 'INV-2026-001',
    schoolName: 'Zenith International Girls Higher Secondary School',
    planName: 'Enterprise Multi-Campus',
    amount: 96000,
    date: '2026-01-01',
    status: 'Paid',
    paymentMethod: 'Net Banking (HDFC)',
  },
  {
    invoiceNo: 'INV-2025-089',
    schoolName: 'Zenith Vidyalaya Matriculation School',
    planName: 'Professional Campus',
    amount: 48000,
    date: '2025-06-01',
    status: 'Paid',
    paymentMethod: 'NEFT Transfer',
  },
  {
    invoiceNo: 'INV-2025-044',
    schoolName: 'Zenith Model Higher Secondary School',
    planName: 'Standard Foundation',
    amount: 24000,
    date: '2025-04-15',
    status: 'Paid',
    paymentMethod: 'UPI / Razorpay',
  },
];

const initialMessages = [
  {
    messageId: 'MSG001',
    senderId: 'USR002',
    senderName: 'R. K. Meenakshi Sundaram',
    senderRole: 'schooladmin',
    receiverId: 'USR004',
    receiverName: 'Mrs. Priya Ramanathan',
    receiverRole: 'teacher',
    schoolId: 'SCH001',
    text: 'Hello Mrs. Priya, please ensure Class 12-A marks are finalized by this Friday.',
    timestamp: '09:15 AM',
    read: true,
  },
  {
    messageId: 'MSG002',
    senderId: 'USR004',
    senderName: 'Mrs. Priya Ramanathan',
    senderRole: 'teacher',
    receiverId: 'USR002',
    receiverName: 'R. K. Meenakshi Sundaram',
    receiverRole: 'schooladmin',
    schoolId: 'SCH001',
    text: 'Good morning sir! Yes, marks verification is almost done and will be submitted today.',
    timestamp: '09:20 AM',
    read: true,
  },
  {
    messageId: 'MSG003',
    senderId: 'USR008',
    senderName: 'S. Krishnan (Parent)',
    senderRole: 'parent',
    receiverId: 'USR004',
    receiverName: 'Mrs. Priya Ramanathan',
    receiverRole: 'teacher',
    schoolId: 'SCH001',
    text: 'Madam, wanted to confirm timings for tomorrow parent-teacher consultation meeting.',
    timestamp: '10:05 AM',
    read: true,
  },
];

const initialTimetable = [
  { schoolId: 'SCH001', grade: 'Class 12', section: 'A', day: 'Monday', period: 1, subject: 'Mathematics', teacherName: 'Mrs. Priya Ramanathan', room: 'Room 301' },
  { schoolId: 'SCH001', grade: 'Class 12', section: 'A', day: 'Monday', period: 2, subject: 'Physics', teacherName: 'Mr. Anand Narayanan', room: 'Physics Lab' },
  { schoolId: 'SCH001', grade: 'Class 12', section: 'A', day: 'Monday', period: 3, subject: 'Chemistry', teacherName: 'Dr. Sunita Sharma', room: 'Chemistry Lab' },
  { schoolId: 'SCH001', grade: 'Class 12', section: 'A', day: 'Monday', period: 4, subject: 'English Core', teacherName: 'Mrs. Deepa Krishnan', room: 'Room 301' },
  { schoolId: 'SCH001', grade: 'Class 12', section: 'A', day: 'Monday', period: 5, subject: 'Computer Science', teacherName: 'Mr. K. Balaji', room: 'Comp Lab 1' },
  { schoolId: 'SCH001', grade: 'Class 12', section: 'A', day: 'Monday', period: 6, subject: 'Physical Education', teacherName: 'Coach R. Selvi', room: 'Sports Ground' },
];

module.exports = {
  initialUsers,
  initialSchools,
  initialStudents,
  initialTeachers,
  initialPlans,
  initialSubscriptions,
  initialBills,
  initialMessages,
  initialTimetable,
};
